version: "3.8"

services:
  traefik:
    image: traefik:v3.1

    command:
      - "--log.level=INFO"

      # EntryPoints
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.metrics.address=:8082"

      # HTTPS redirect
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"

      # Providers
      - "--providers.docker=true"
      - "--providers.docker.swarmMode=true"
      - "--providers.docker.exposedbydefault=false"

      - "--providers.file.directory=/etc/traefik/dynamic"
      - "--providers.file.watch=true"

      # Dashboard
      - "--api.dashboard=true"
      - "--api.insecure=false"

      # Metrics
      - "--metrics.prometheus=true"
      - "--metrics.prometheus.entrypoint=metrics"

      # ===== ACME（关键）=====
      - "--certificatesresolvers.le.acme.email=admin@wuyuan.dev"
      - "--certificatesresolvers.le.acme.dnschallenge=true"
      - "--certificatesresolvers.le.acme.dnschallenge.provider=cloudflare"

      # ACME 使用 Consul 作为存储
      - "--certificatesresolvers.le.acme.storage=consul://consul:8500/traefik/acme"

    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./dynamic:/etc/traefik/dynamic:ro

    environment:
      - CF_DNS_API_TOKEN_FILE=/run/secrets/cf_dns_api_token

    secrets:
      - cf_dns_api_token
      - traefik-dashboard-users

    deploy:
      mode: global


    networks:
      - traefik-net

secrets:
  cf_dns_api_token:
    external: true
  traefik-dashboard-users:
    external: true

networks:
  traefik-net:
    external: true
